package friendly.backend

/**
 * July feature to publicly invite people in Friendly.
 * It has a bunch of hardcoded invite links that are active in July 2026.
 */
object PermanentLinks {
    val Vestibule = Record(
        token = FriendToken.orThrow(
            "VESTIBULE_SOCIAL_NETWORK_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        ),
        userId = UserId(904),
    )

    val Ru = Record(
        token = FriendToken.orThrow(
            "RU_SOCIAL_NETOWRK_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        ),
        userId = UserId(905),
    )

    val Entries = listOf(Vestibule, Ru)

    data class Record(val token: FriendToken, val userId: UserId)
}
